const data = {
    "baza": [
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-1",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7136735006S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8L1)",
            "Engine Type": "1.9 TDI",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "09.1996",
            "ENG. EOP": "07.2001",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-2",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7136735007S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8L1)",
            "Engine Type": "1.9 TDI",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "09.1996",
            "ENG. EOP": "07.2001",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-3",
            "Turbocharger PN": "7534205005S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "FORD",
            "Veh.Type": "FOCUS C-MAX",
            "Engine Type": "1.6 TDCi",
            "KW": "80",
            "HP": "109",
            "ENG. SIZE": "1560",
            "No of Cylinder": "4",
            "ENG. SOP": "10.2003",
            "ENG. EOP": "03.2007",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-4",
            "Turbocharger PN": "7534205006S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "FORD",
            "Veh.Type": "FOCUS C-MAX",
            "Engine Type": "1.6 TDCi",
            "KW": "80",
            "HP": "109",
            "ENG. SIZE": "1560",
            "No of Cylinder": "4",
            "ENG. SOP": "10.2003",
            "ENG. EOP": "03.2007",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-5",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7518515004S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "VW",
            "Veh.Type": "TOURAN (1T1, 1T2)",
            "Engine Type": "1.9 TDI",
            "KW": "74",
            "HP": "100",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "02.2003",
            "ENG. EOP": "05.2004",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-6",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7178585010S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A4 (8D2, B5)",
            "Engine Type": "1.9 TDI",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "01.1995",
            "ENG. EOP": "11.2000",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-7",
            "Turbocharger PN": "7069775001S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "PEUGEOT",
            "Veh.Type": "406 (8B)",
            "Engine Type": "2.0 HDI 110",
            "KW": "80",
            "HP": "109",
            "ENG. SIZE": "1997",
            "No of Cylinder": "4",
            "ENG. SOP": "06.1998",
            "ENG. EOP": "08.2001",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-8",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7136725006S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8L1)",
            "Engine Type": "1.9 TDI",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "09.1996",
            "ENG. EOP": "07.2001",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-9",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7136725007S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8L1)",
            "Engine Type": "1.9 TDI",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "09.1996",
            "ENG. EOP": "07.2001",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-10",
            "Turbocharger PN": "7517685004S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "OPEL",
            "Veh.Type": "VIVARO Camion plate-forme/Châssis (E7)",
            "Engine Type": "1.9 Di",
            "KW": "60",
            "HP": "82",
            "ENG. SIZE": "1870",
            "No of Cylinder": "4",
            "ENG. SOP": "08.2006",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-11",
            "Turbocharger PN": "7517685005S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "OPEL",
            "Veh.Type": "VIVARO Camion plate-forme/Châssis (E7)",
            "Engine Type": "1.9 Di",
            "KW": "60",
            "HP": "82",
            "ENG. SIZE": "1870",
            "No of Cylinder": "4",
            "ENG. SOP": "08.2006",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-12",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7249305006S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8P1)",
            "Engine Type": "2.0 TDI 16V",
            "KW": "103",
            "HP": "140",
            "ENG. SIZE": "1968",
            "No of Cylinder": "4",
            "ENG. SOP": "05.2003",
            "ENG. EOP": "08.2012",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-13",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7249305009S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8P1)",
            "Engine Type": "2.0 TDI 16V",
            "KW": "103",
            "HP": "140",
            "ENG. SIZE": "1968",
            "No of Cylinder": "4",
            "ENG. SOP": "05.2003",
            "ENG. EOP": "08.2012",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-14",
            "Turbocharger PN": "4542315007S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A4 (8D2, B5)",
            "Engine Type": "1.9 TDI",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1896",
            "No of Cylinder": "4",
            "ENG. SOP": "01.1995",
            "ENG. EOP": "11.2000",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-15",
            "Turbocharger PN": "7069765001S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "CITROËN",
            "Veh.Type": "XSARA PICASSO (N68)",
            "Engine Type": "2.0 HDi",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1997",
            "No of Cylinder": "4",
            "ENG. SOP": "12.1999",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-16",
            "VNT PN": "Otkovak",
            "Turbocharger PN": "7755175001S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "SEAT",
            "Veh.Type": "LEON (1P1)",
            "Engine Type": "1.6 TDI",
            "KW": "77",
            "HP": "105",
            "ENG. SIZE": "1598",
            "No of Cylinder": "4",
            "ENG. SOP": "02.2010",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-17",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7249305012S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "AUDI",
            "Veh.Type": "A3 (8P1)",
            "Engine Type": "2.0 TDI 16V",
            "KW": "103",
            "HP": "140",
            "ENG. SIZE": "1968",
            "No of Cylinder": "4",
            "ENG. SOP": "05.2003",
            "ENG. EOP": "08.2012",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-18",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7064999004S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "FORD",
            "Veh.Type": "FOCUS (DAW, DBW)",
            "Engine Type": "1.8 Turbo DI / TDDi",
            "KW": "66",
            "HP": "90",
            "ENG. SIZE": "1753",
            "No of Cylinder": "4",
            "ENG. SOP": "10.1998",
            "ENG. EOP": "11.2004",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-19",
            "VNT PN": "704013-0025",
            "Turbocharger PN": "7607745003S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "FORD",
            "Veh.Type": "MONDEO IV Turnier",
            "Engine Type": "2.0 TDCi",
            "KW": "100",
            "HP": "136",
            "ENG. SIZE": "1997",
            "No of Cylinder": "4",
            "ENG. SOP": "03.2007",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "Remanufactured Turbocharger",
            "RE-TURBO PN": "XX-20",
            "Turbocharger PN": "7991715002S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "CITROËN",
            "Veh.Type": "NEMO Camionnette (AA_)",
            "Engine Type": "1.3 HDi 75",
            "KW": "55",
            "HP": "75",
            "ENG. SIZE": "1248",
            "No of Cylinder": "4",
            "ENG. SOP": "10.2010",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-21",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "7086395010S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "VOLVO",
            "Veh.Type": "S40 I (VS)",
            "Engine Type": "1.9 DI",
            "KW": "75",
            "HP": "102",
            "ENG. SIZE": "1870",
            "No of Cylinder": "4",
            "ENG. SOP": "07.2000",
            "ENG. EOP": "12.2003",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-22",
            "VNT PN": "704013-0025",
            "Turbocharger PN": "7560475005S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "PEUGEOT",
            "Veh.Type": "508",
            "Engine Type": "2.0 HDi",
            "KW": "100",
            "HP": "136",
            "ENG. SIZE": "1997",
            "No of Cylinder": "4",
            "ENG. SOP": "11.2010",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-23",
            "VNT PN": "717505-0026",
            "Turbocharger PN": "7678355001S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "OPEL",
            "Veh.Type": "ASTRA H Van",
            "Engine Type": "1.9 CDTI",
            "KW": "88",
            "HP": "120",
            "ENG. SIZE": "1910",
            "No of Cylinder": "4",
            "ENG. SOP": "09.2005",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-24",
            "VNT PN": "743595-0025",
            "Turbocharger PN": "7651555007S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "MERCEDES-BENZ",
            "Veh.Type": "CLASSE M (W164)",
            "Engine Type": "ML 280 CDI 4-matic (164.120)",
            "KW": "140",
            "HP": "190",
            "ENG. SIZE": "2987",
            "No of Cylinder": "6",
            "ENG. SOP": "07.2005",
            "ENG. EOP": "07.2009",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-25",
            "VNT PN": "717505-0026",
            "Turbocharger PN": "7663405001S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "OPEL",
            "Veh.Type": "ASTRA H Van",
            "Engine Type": "1.9 CDTI",
            "KW": "110",
            "HP": "150",
            "ENG. SIZE": "1910",
            "No of Cylinder": "4",
            "ENG. SOP": "09.2004",
            "ENG. EOP": "0",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-26",
            "VNT PN": "716768-0002",
            "Turbocharger PN": "7406115002S",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "HYUNDAI",
            "Veh.Type": "i30 CW (FD)",
            "Engine Type": "1.6 CRDi",
            "KW": "94",
            "HP": "128",
            "ENG. SIZE": "1582",
            "No of Cylinder": "4",
            "ENG. SOP": "01.2010",
            "ENG. EOP": "06.2012",
            "FUEL": "DIESEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-27",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "Audi",
            "Veh.Type": "0",
            "Engine Type": "2.5 V6 TDI",
            "KW": "110",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-28",
            "VNT PN": "743595-0025",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "Audi",
            "Veh.Type": "0",
            "Engine Type": "2.5 V6 TDI",
            "KW": "114-132",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-29",
            "VNT PN": "704013-0025",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "BMW",
            "Veh.Type": "M47 ",
            "Engine Type": "2",
            "KW": "110",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-30",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "BMW",
            "Veh.Type": "M57 ",
            "Engine Type": "3",
            "KW": "135/142",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-31",
            "VNT PN": "704013-0020",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "FORD",
            "Veh.Type": "0",
            "Engine Type": "1.8 TDCI",
            "KW": "74-85",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-32",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "HYUNDAI",
            "Veh.Type": "0",
            "Engine Type": "2.0 CRDI",
            "KW": "103",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-33",
            "VNT PN": "704013-0025",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "Nissan",
            "Veh.Type": "0",
            "Engine Type": "2.2DCI ",
            "KW": "100",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-34",
            "VNT PN": "704013-0025",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "Renault",
            "Veh.Type": "G9T ",
            "Engine Type": "2.2DCI",
            "KW": "110",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-35",
            "VNT PN": "704013-0025",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "Toyota",
            "Veh.Type": "Corolla/Avensis",
            "Engine Type": "2.0 D4-D",
            "KW": "0",
            "HP": "0",
            "ENG. SIZE": "0",
            "No of Cylinder": "0",
            "ENG. SOP": "0",
            "ENG. EOP": "0",
            "FUEL": "0"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-36",
            "VNT PN": "716768-0002",
            "Turbocharger PN": "753420-8",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "PSA"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-37",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "708639-0010 ",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "Renault"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-38",
            "VNT PN": "704013-0020",
            "Turbocharger PN": "724930-9",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "VAG"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-39",
            "Turbocharger PN": "49135-05640",
            "Turbocharger Manufacturer": "MHI",
            "CAR MAKER": "BMW"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-40",
            "VNT PN": "704013-0025",
            "Turbocharger PN": "756047-5",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "PSA"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-41",
            "VNT PN": "780084-0009",
            "Turbocharger PN": "798128-8"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-42",
            "Turbocharger PN": "767933-15"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-43",
            "VNT PN": "780084-0009",
            "Turbocharger PN": "790179-2",
            "Turbocharger Manufacturer": "GARRETT"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-44",
            "VNT PN": "743595-0025",
            "Turbocharger PN": "765155-7",
            "CAR MAKER": "Mercedes"
        },
        {
            "PRODUCT": "Ring",
            "RE-TURBO PN": "XX-45",
            "VNT PN": "717506-0027",
            "Turbocharger PN": "752610-10",
            "CAR MAKER": "FORD"
        },
        {
            "PRODUCT": "Disc",
            "RE-TURBO PN": "XX-46",
            "Turbocharger PN": "767835-3",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "OPEL"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-47",
            "VNT PN": "758663-0015",
            "Turbocharger PN": "765261-3",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "VAG"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-48",
            "Turbocharger PN": "758351-0024",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "BMW"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-49",
            "VNT PN": "717506-0023",
            "Turbocharger PN": "709837-2",
            "CAR MAKER": "Mercedes"
        },
        {
            "PRODUCT": "VNT",
            "RE-TURBO PN": "XX-50",
            "VNT PN": "780084-0009",
            "Turbocharger PN": "757042-11",
            "Turbocharger Manufacturer": "GARRETT",
            "CAR MAKER": "VAG"
        }
    ]
}